### ISSUE TITLE
gps관련 글 잘봤습니다 테스트 도중에 에러가 발생해서 남깁니다

### ISSUE THREAD

**Issue by chonamdoo** [brownsoo/Choosing-Android-Location-API#2]
java.lang.UnsupportedOperationException
                                                                                        at java.util.AbstractList.add(AbstractList.java:148)
                                                                                        at java.util.AbstractList.add(AbstractList.java:108)
                                                                                        at com.hansoolabs.test.locationupdate.utils.LocationStabilizer.checkLevelWithRegions(LocationStabilizer.java:207)
                                                                                        at com.hansoolabs.test.locationupdate.utils.LocationStabilizer.getLocationLevel(LocationStabilizer.java:116)
                                                                                        at com.hansoolabs.test.locationupdate.utils.LocationStabilizer.isStableLocation(LocationStabilizer.java:63)
                                                                                        at com.hansoolabs.test.locationupdate.MainActivity.lambda$-com_hansoolabs_test_locationupdate_MainActivity_lambda$4(MainActivity.java:918)
                                                                                        at com.hansoolabs.test.locationupdate.-$Lambda$7.$m$0(Unknown Source)
                                                                                        at com.hansoolabs.test.locationupdate.-$Lambda$7.run(Unknown Source)
                                                                                        at android.app.Activity.runOnUiThread(Activity.java:5866)
                                                                                        at com.hansoolabs.test.locationupdate.MainActivity.traceLocation(MainActivity.java:879)
                                                                                        at com.hansoolabs.test.locationupdate.MainActivity.lambda$-com_hansoolabs_test_locationupdate_MainActivity_lambda$1(MainActivity.java:688)
                                                                                        at com.hansoolabs.test.locationupdate.-$Lambda$0.$m$0(Unknown Source)
                                                                                        at com.hansoolabs.test.locationupdate.-$Lambda$0.onLocationChanged(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzasg$zzb$1.zza(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzasg$zzb$1.zzs(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzabh.zzb(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzabh$zza.handleMessage(Unknown Source)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by brownsoo** [comment]
감사합니다. 확인해보겠습니다~
